server {
   listen 80;
   server_name frontend;
   
   location / {
      otel_trace         on;
      otel_trace_context extract;
      
      otel_span_name "$request_method $request_uri";
      
      proxy_pass https://%CODEFORCES_CONTEST.contest.codeforces.com;
      proxy_set_header Host %CODEFORCES_CONTEST.contest.codeforces.com;
      proxy_ssl_protocols TLSv1.2 TLSv1.3;
      proxy_ssl_server_name on;
      proxy_ssl_name %CODEFORCES_CONTEST.contest.codeforces.com;

      proxy_cookie_flags * secure HttpOnly SameSite=None;
      proxy_pass_header Set-Cookie;
      proxy_set_header Cookie $http_cookie;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Referer https://%CODEFORCES_CONTEST.contest.codeforces.com;
      proxy_set_header Origin https://%CODEFORCES_CONTEST.contest.codeforces.com;
   }
}