# Generated by Django 5.1.5 on 2025-03-22 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(verbose_name='room_id')),
                ('row', models.IntegerField(verbose_name='row_id')),
                ('column', models.IntegerField(verbose_name='column_id')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(unique=True, verbose_name='Team UUID')),
                ('team_name', models.TextField(unique=True, verbose_name='Team Name')),
                ('team_location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='teams.teamlocation', verbose_name='Team Location')),
            ],
        ),
    ]
