# Generated by Django 5.1.5 on 2025-03-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_slug',
            field=models.TextField(default='', unique=True, verbose_name='Team Slug'),
            preserve_default=False,
        ),
    ]
