# Generated by Django 5.1.5 on 2025-03-23 11:04

import django.db.models.deletion
import django_enumfield.db.fields
import printout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='URL')),
                ('code', models.TextField(verbose_name='Code')),
                ('status', django_enumfield.db.fields.EnumField(enum=printout.models.PrintoutStatus)),
                ('target', models.TextField(verbose_name='Bucket Target')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
        ),
    ]
