# Generated by Django 5.1.5 on 2025-03-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printout',
            name='user',
            field=models.TextField(default='', verbose_name=''),
        ),
    ]
